[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd sarthi-backend && npm install --include=dev"]

[phases.build]
cmds = ["cd sarthi-backend && npm run build"]

[start]
cmd = "cd sarthi-backend && node dist/main"
